### ISSUE TITLE
Sync Labels

### ISSUE THREAD

**Issue by husamettinarabaci** [octoposprime/op-be-dlr#4]
Please sync all labels from 
https://github.com/orgs/octoposprime/discussions/14

Names and Colors

**Comment by Sddilora** [comment]
Does the phrase "Names and colors" indicate that we should not include the description part?. Also, some of the labels are subject-specific. Should we also add them to our repositories?
@husamettinarabaci

**Comment by husamettinarabaci** [comment]
You have to sync all names, colors, and descriptions.

https://github.com/orgs/octoposprime/discussions/14#discussioncomment-9026048

**Comment by husamettinarabaci** [comment]
You have to sync all names, colors, and descriptions.

https://github.com/orgs/octoposprime/discussions/14#discussioncomment-9026048

**Comment by Feyzanrs** [comment]
labels synced
